name: Add comment on pull request
on:
  pull_request:
    types: [closed]
jobs:
  add-label:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4.0
        with:
          script: |
            github.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ["release-ready"]
              });
  add-comment:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Add comment
        uses: peter-evans/create-or-update-comment@5f728c3dae25f329afbe34ee4d08eef25569d79f
        with:
          issue-number: ${{ github.event.pull_request.number }}
          reactions: eyes, rocket
          body: |
            Thank you for your contribution! :sparkles:
