name: Add comment on pull request
on:
  # pull_request:
  #   types:
  #     - labeled
  push:
  branches:
    - main
jobs:
  add-comment:
    if: github.event.label.name == 'release-ready'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Add comment
        uses: peter-evans/create-or-update-comment@5f728c3dae25f329afbe34ee4d08eef25569d79f
        with:
          issue-number: ${{ github.event.pull_request.number }}
          reactions: eyes, rocket
          body: |
            Thank you for your contribution! :sparkles:
